[book]
authors = ["andymac4182"]
language = "en"
multilingual = false
src = "src"
title = "Obsidian Confluence Integration"
create-missing = false


[output.html]
git-repository-url = "https://github.com/obsidian-confluence/obsidian-confluence"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/obsidian-confluence/obsidian-confluence/edit/main/docs/{path}"
cname = "obsidian-confluence.com"

