[book]
authors = ["andymac4182"]
language = "en"
multilingual = false
src = "src"
title = "Obsidian Confluence Integration"

[output.html]
git-repository-url = "https://github.com/rust-lang/mdBook"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
cname = "obsidian-confluence.com"

