name: Release Obsidian plugin

on:
  push:
    branches:
      - main

env:
  PLUGIN_NAME: obsidian-confluence # Change this to match the id of your plugin.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x" # You might need to adjust this value to your own version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      # Get the version number and put it in an environment file
      - name: Get Version
        id: version
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      # Build the plugin
      - name: Build
        id: build
        run: |
          sed -i "s/0\.0\.0/${{ env.tag }}/g" manifest.json
          npm ci
          npm run build --if-present
          zip -r ${{ github.event.repository.name }}-${{ env.tag }}.zip dist

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: |
#            ${{ github.event.repository.name }}-${{ env.tag }}.zip
#            dist/main.js
#            dist/manifest.json
