on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@v3

      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
      
      - name: Use Node.js
        if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: 'https://registry.npmjs.org'

      - name: Latest NPM
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm install -g npm@latest

      - name: Upload release assets
        if: ${{ steps.release-please.outputs.release_created }}
        run: ./.build/upload-release-assets.sh ${{ steps.release-please.outputs.tag_name }} ${{ steps.release-please.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to NPM
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          npm publish -w @markdown-confluence/lib
          npm publish -w @markdown-confluence/mermaid-electron-renderer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
